# Generated by Django 2.2.6 on 2019-10-25 10:17

from django.db import migrations, models
import django_powerbank.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Recipient email address', max_length=254, verbose_name='email')),
                ('secret', django_powerbank.db.models.fields.SecretField(help_text='Autogenerated password for the shared data', max_length=20, verbose_name='secret')),
                ('file', models.FileField(blank=True, help_text='File to share', null=True, upload_to='', verbose_name='file')),
            ],
            options={
                'verbose_name': 'shared file',
                'verbose_name_plural': 'shared file',
                'default_related_name': 'shared_files',
            },
        ),
        migrations.CreateModel(
            name='SharedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Recipient email address', max_length=254, verbose_name='email')),
                ('secret', django_powerbank.db.models.fields.SecretField(help_text='Autogenerated password for the shared data', max_length=20, verbose_name='secret')),
                ('url', models.URLField(blank=True, help_text='Url to share', null=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'shared url',
                'verbose_name_plural': 'shared url',
                'default_related_name': 'shared_urls',
            },
        ),
    ]
