# Generated by Django 2.2.6 on 2019-10-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='sharedurl',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
